### ISSUE TITLE
[아이템 3] 리플렉션 API 방어 로직 작성 시 던지는 예외의 종류

### ISSUE THREAD

**Issue by HaeUlNam** [coukieStudy/Effective-Java#3]
코드 3-1의 경우 reflection으로 private 생성자를 호출할 수 있는데, 이에 대한 구현은 아래와 같이 될 수 있다고 생각합니다.

```java
public class Elvis {
   public static final Elvis INSTANCE = new Elvis();
   private Elvis() {
      if(INSTANCE != null){
          //throw exception
      } 
   }
   
   public void leaveTheBuilding() { ... } 
}
```

위의 경우에서 어떤 exception을 던지는 것이 적합할지 궁금합니다.

**Comment by david1403** [comment]
제가 찾아본 바로는 그냥 RuntimeException을 throw 하는 예외도 있었고 (https://medium.com/@kevalpatel2106/how-to-make-the-perfect-singleton-de6b951dfdb0) 객체의 생성과 관련된 예외이니 InstantiationException을 throw 하는 것도 적절해 보입니다.
https://docs.oracle.com/javase/8/docs/api/java/lang/InstantiationException.html
