### ISSUE TITLE
[아이템 3] 정적 팩터리의 메서드 참조를 공급자(Supplier)로 사용

### ISSUE THREAD

**Issue by HaeUlNam** [coukieStudy/Effective-Java#4]
제가 이해한 바로는 공급자(Supplier)로 사용한다는 것이 아래와 같이 사용한다는 것인데, 왜 굳이 Supplier로 받아서 사용할까요?
Elvis의 getInstance을 단독으로 사용해도 충분할 것으로 생각했는데, Supplier로 사용할 경우 어떤 장점이 존재하는지 궁금합니다.
```java
Supplier<Elvis> elvisSupplier = Elvis::getInstance;
Elvis elvis = elvisSupplier.get();
```

**Comment by fuzzysound** [comment]
Supplier 타입으로서 사용할 수 있다는 의미인 것 같습니다.
예를 들어서 `Chef`라는 클래스의 `cook`이라는 메서드가 `Dish` 인터페이스의 구현체를 리턴하는 정적 팩터리 메서드를 파라미터로 필요로 한다고 하면
```java
public class Chef {
    public <T extends Dish> T cook(Supplier<T> recipe) {}
}
```
이런 식으로 타입을 Supplier로 지정해서 메서드를 파라미터로 넘길 수 있겠죠. 제네릭으로 타입 안전성도 확보할 수 있구요. static final 필드로는 이렇게 만들기 어려울 거에요.
