### ISSUE TITLE
[아이템 4] final 클래스와 관련한 메서드들을 모아놓을 때 정적 메서드와 정적 필드만을 담은 클래스 사용

### ISSUE THREAD

**Issue by HaeUlNam** [coukieStudy/Effective-Java#5]
왜 final 클래스와 관련한 메서드들을 모아놓는 건지 이해가 잘 되지 않습니다.. 실제 예시를 통해 이 부분에 대해 설명해주시면 감사하겠습니다.

**Comment by fuzzysound** [comment]
`java.lang.Math`랑 `java.lang.StrictMath` 참고하세요.
