### ISSUE TITLE
[아이템3] singleton class의 unitTest 

### ISSUE THREAD

**Issue by briggirl2** [coukieStudy/Effective-Java#6]
23p. 싱글턴 인스턴스를 mock 구현으로 대체할 수 없다.<br>

그렇다면 unitTest는 어떻게 하나요? injectMock으로도 안되는건가요?

**Comment by fuzzysound** [comment]
인스턴스를 mock해서 테스트 때 사용할 순 있으나 그 인스턴스가 싱글턴임을 보장할 순 없습니다.
