### ISSUE TITLE
[Item 6] 불필요한 Long 인스턴스가 약 231개

### ISSUE THREAD

**Issue by HaeUlNam** [coukieStudy/Effective-Java#7]
코드 6-3을 실행시키면 불필요한 Long 인스턴스가 약 231개 생성된다고 하는데, long 타입인 i가 MAX_VALUE번 더해지는 것이 아닌가요?
자체적으로 최적화해서 231번만 더해지도록 하는 것인지 궁금합니다.

**Comment by JJerryChoi** [comment]
2^31의 오타입니다.
