### ISSUE TITLE
[Item 5] 스프링에서 의존 객체 주입의 예시

### ISSUE THREAD

**Issue by fuzzysound** [coukieStudy/Effective-Java#8]
제가 스프링을 안 써봐서 그러는데, 스프링에서 의존 객체 주입을 어떻게 활용하고 있는지 예시를 알고 싶습니다.

**Comment by HaeUlNam** [comment]
Spring 내부에 IOC(Inversion Of Control) 컨테이너에서 객체의 라이프사이클을 책임지며, 객체를 주입해주는 역할을 하게 됩니다.
Spring에 DI 방법은 [여러가지](https://coding-start.tistory.com/250)가 있지만, 그 중에 best-pratices라고 여겨지는 생성자를 통한 주입을 예로 들겠습니다.
```java
@Component
public class PetOwner{
    private AnimalType animal;

    public PetOwner(AnimalType animal) {
        this.animal = animal;
    }
}
```
위와 같이 생성자를 통해, Spring Framework에서 의존 객체 주입해주게 됩니다. 이 때, AnimalType은 IOC 컨테이너에 의해 관리되고 있는 Bean이어야만 가능합니다. 아니라면 에러 발생.

따라서 의존 객체 관리를 Framework에서 해주기 때문에, 코드를 더 편리하게 작성할 수 있습니다.

**Comment by briggirl2** [comment]
https://private.tistory.com/39
