### ISSUE TITLE
[아이템 7] 콜백의 회수

### ISSUE THREAD

**Issue by fuzzysound** [coukieStudy/Effective-Java#9]
이번 아이템 말미에 이런 설명이 있는데요,
"이럴 때 콜백을 약한 참조로 저장하면 가비지 컬렉터가 즉시 수거해간다."
이 말인즉슨 콜백에 들어갈 함수를 약한 참조로 저장하고 나중에 필요없어지면 null로 선언하면 된다는 건가요?
만약 그렇다면 그런 식으로 하느니 차라리 콜백을 해지(unregister)하는 방법을 쓰는 게 낫지 않나요?

**Comment by HaeUlNam** [comment]
지역 변수를 사용하면 해당 scope을 벗어날 때 자동으로 해지되는 경우를 뜻하는 것 같아요.
즉, WeakReference보다 Callback의 생애주기가 더 짧을 때 유용하게 사용할 수 있겠죠. (아래는 Callback 예제는 아니지만, 아래와 비슷한 방식일 듯하네요)

![스크린샷 2020-09-07 오후 8 39 44](https://user-images.githubusercontent.com/26040955/92383993-44a8ab80-f14a-11ea-842c-c3a5c44eb564.png)
